# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbelt', '0002_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='favorite_quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='fan',
            field=models.ManyToManyField(related_name='favorite_quotes', to='pbelt.User'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
